train-size-coefficient: 0.7
nodes:
    - 16
    - 24
    - 32
    - 64
    - 128
weights:
    - 1.
    - 5.
    - 10.
    - 15.
    - 20.
    - 25.
    - 50.
epochs:
    - 100
    - 200
    - 500
